easy_admin:
    list:
        actions: ['show']
    entities:
        # List the entity class name you want to manage
        - App\Entity\Order
#        - App\Entity\Category
#        - App\Entity\User
